import { pgTable, text } from 'drizzle-orm/pg-core';
import { serverTimestamp, utcTimestamp } from './columns.js';
import { users } from './users.js';

/**
 * better-auth's required tables (Phase 3).
 *
 * better-auth owns credentials and sessions; these three tables back its core
 * models. The Drizzle adapter is wired to them in `src/auth/auth.ts` by mapping
 * model name → table object, so the table *names* here are our choice — we keep
 * them singular (`session`/`account`/`verification`) to match better-auth's own
 * generated SQL and stay greppable.
 *
 * IMPORTANT: the JS property keys MUST match the field names better-auth expects
 * (camelCase: `userId`, `expiresAt`, `accountId`, …). The adapter resolves
 * columns by those keys; the snake_case DB column names are free to follow our
 * convention. Primary keys are plain `text` with NO app-side default — ids are
 * generated by better-auth itself (NOT our prefixed `id()` helper), which owns
 * identity for everything it writes (user/session/account/verification rows).
 *
 * `users` is intentionally not redefined here (Phase 2 already created a
 * better-auth-compatible table); FKs below cascade so deleting a user clears
 * their sessions and linked accounts.
 */

/** better-auth `session` model — one row per active login session. */
export const sessions = pgTable('session', {
  id: text('id').primaryKey(),
  token: text('token').notNull().unique(),
  expiresAt: utcTimestamp('expires_at').notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  createdAt: serverTimestamp('created_at'),
  updatedAt: serverTimestamp('updated_at'),
});

export type Session = typeof sessions.$inferSelect;

/**
 * better-auth `account` model — one row per credential or linked OAuth account.
 * Email/password hashes live in `password` here (NOT on `users`); GitHub logins
 * store `accessToken`/`refreshToken`/`idToken` and the provider account id.
 *
 * Exported as `authAccounts`/`AuthAccount` (NOT `accounts`/`Account`) to stay
 * unambiguously distinct from the billing-tenant table `billing_accounts`
 * (`billingAccounts`/`BillingAccount`). The DB table name stays `account`
 * (singular) to match better-auth's own generated SQL.
 */
export const authAccounts = pgTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: utcTimestamp('access_token_expires_at'),
  refreshTokenExpiresAt: utcTimestamp('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: serverTimestamp('created_at'),
  updatedAt: serverTimestamp('updated_at'),
});

export type AuthAccount = typeof authAccounts.$inferSelect;

/**
 * better-auth `verification` model — short-lived tokens for email verification
 * and password reset. No FK to `users` (identifier is an email/opaque key).
 */
export const verifications = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: utcTimestamp('expires_at').notNull(),
  createdAt: serverTimestamp('created_at'),
  updatedAt: serverTimestamp('updated_at'),
});

export type Verification = typeof verifications.$inferSelect;
